version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Waiting for Sonarqube to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 9000 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Sonarqube && exit 1
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      # run tests!
      - run: gradle test
      - run: gradle -Dsonar.host.url=http://localhost:9000 --debug --scan sonar
      - store_artifacts:
          path: /jacocoHtml
